### PR TITLE
Add info

### PR DESCRIPTION
**Pull request by AwayFromKeyword**
just a tiny change

### CODE REVIEW

**Comment by retronbv** [comment]
What is the point of this

**Comment by AwayFromKeyword** [comment]
> What is the point of this

Just a minor change to tell people what to do with the icons

**Comment by Explosion-Scratch** [comment]
sorry I have to close and reopen to re-run stuff

**Comment by Explosion-Scratch** [comment]
Uhmmmmm you know that index.html's `#readme` section is auto generated, right?? (By the all-contributors bot and showdownjs which fetches the raw README)

**Pull request closed without merging**
