### PR TITLE
Crap

### PR DESCRIPTION
**Pull request by AmpersandGD**
mah bois

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
Wait, what does this add?

**Comment by Explosion-Scratch** [comment]
I'm happy with the README as is btw, if there's anything else that this adds please tell me! Also do not hesitate to message me on discord when you make a PR

**Comment by retronbv** [comment]
I think this is a pr to pull the newest changes, but accidentally using the wrong sources.

**Comment by retronbv** [comment]
@AmpersandGD Does yarn work for bijou?

**Comment by AmpersandGD** [comment]
> I'm happy with the README as is btw, if there's anything else that this adds please tell me! Also do not hesitate to message me on discord when you make a PR


I was locked out of my discord account, so no

**Comment by AmpersandGD** [comment]
> @AmpersandGD Does yarn work for bijou?

Yes

**Comment by retronbv** [comment]
> > @AmpersandGD Does yarn work for bijou?
> 
> Yes

ok

**Comment by Explosion-Scratch** [comment]
Yarn works for Bijou!
`yard add bijou.js` 
done. Boom.

**Comment by AmpersandGD** [comment]
So we gonna merge or what?

**Pull request merged**
