### PR TITLE
Rollup

### PR DESCRIPTION
**Pull request by ZI-Youtuber**

### CODE REVIEW

**Comment by AwayFromKeyword** [comment]
You literally deleted the entirety of `bijou.js`

**Comment by retronbv** [comment]
This isn’t even your code? It’s @GrahamSH-LLK’s

**Comment by AwayFromKeyword** [comment]
Lol

**Comment by retronbv** [comment]
Explainaition?

**Comment by Explosion-Scratch** [comment]
XD You didn't do anything?

**Comment by retronbv** [comment]
> XD You didn't do anything?

It’s entirely Graham’s code from last month

**Comment by Explosion-Scratch** [comment]
> You literally deleted the entirety of `bijou.js`

🤣 😭

**Comment by Explosion-Scratch** [comment]
> > XD You didn't do anything?
> 
> It’s entirely Graham’s code from last month

@ZI-Youtuber May have been testing PR's? There's no description though lol

**Comment by retronbv** [comment]
Very much confusing.

**Comment by Explosion-Scratch** [comment]
In the future @ZI-Youtuber please make sure to contribute your own code, and at least attribute or explain when you use other's code.

**Comment by retronbv** [comment]
@GrahamSH-LLK is it fine if I delete the branch? (It’s from last month soooo)

**Pull request closed without merging**
