### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Explosion-Scratch**
test please approve or request changes

### CODE REVIEW

**Review by Explosion-1 — APPROVED** [review]
Test

**Review by Explosion-1 — APPROVED** [review]
testing again

**Review by Explosion-1 — APPROVED** [review]

**Comment by Explosion-Scratch** [comment]
YESYESYES

**Review by Explosion-1 — CHANGES_REQUESTED** [review]
lol

**Review by TheColaber — APPROVED** [review]
bruh

**Review by Explosion-1 — CHANGES_REQUESTED** [review]
I love this action

**Pull request merged**
