### PR TITLE
Merge pull request #1 from Bijou-js/main

### PR DESCRIPTION
**Pull request by D1WK**
Uptodateify.....again (you guys are commiting too fast for my fork lol)

### CODE REVIEW

**Comment by D1WK** [comment]
woops

**Comment by D1WK** [comment]
nvm

**Comment by YOYITsM3M8** [comment]
I’m confused ^.^

**Comment by Explosion-Scratch** [comment]
What?

**Comment by D1WK** [comment]
I mean my fork is outdated

**Pull request closed without merging**
