### PR TITLE
Grammar Issue

### PR DESCRIPTION
**Pull request by AwayFromKeyword**

### CODE REVIEW

**Review by retronbv — APPROVED** [review]
Please better title/description

**Comment by pufferfish101007** [comment]
The original wasn't actually incorrect.

**Review by ZI-Youtuber — APPROVED** [review]

**Review by ZI-Youtuber — APPROVED** [review]

**Comment by AwayFromKeyword** [comment]
> The original wasn't actually incorrect.

It just looks tidier.
dOn'T fOrGeT yOuR cOmMaS kIdS

**Pull request merged**
